


# Select image from https://hub.docker.com/_/php/
image: php:7.4

# Select what we should cache
cache:
  paths:
    - vendor/

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null

# We test PHP5.6
test:5.6:
  image: php:5.6
  script:
    - phpunit --configuration phpunit_myapp.xml
  allow_failure: true

# We test PHP7.0 (good luck with that)
test:7.4:
  image: php:7.4
  script:
    - phpunit --configuration phpunit_myapp.xml

