stages:
  - build
  - test
  - deploy

composer:
  stage: build
  image: php:7.4-cli
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - apt-get update && apt-get upgrade -y &&  apt-get install -y php-xdebug git libzip-dev
    - docker-php-ext-configure zip
    - docker-php-ext-install zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/


testing:
  stage: test
  needs: [composer]
  image: php:7.4-cli
  script:
    - ./vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --coverage-text
